### ISSUE TITLE
[Request] Ignore Main Search

### ISSUE THREAD

**Issue by livejamie** [JonasRock/POETradeFuzzySearch#4]
I love this extension for searching mods, but it's frustrating to use in the main search for items I know the name of.

I would love for it to be disabled or togglable.

**Comment by JonasRock** [comment]
Hi, thank you for your suggestions.

It is already possible to not use the fuzzy search for any query by simply starting the search with a space. (e.g. " tabula" instead of "tabula", note the space in front).
No tilde will be added to any query starting with a space for this exact usecase (although it is certainly not well documented).

Toggling the fuzzy search on or off using a visual button would certainly be a good feature to have, but is unfortunately a little out of scope for me at the moment.

Hope this helps!
